name: card_game
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.19.0 # ou a versão mais recente compatível
  flame_audio: ^1.0.0 # Para efeitos sonoros, se necessário
  cupertino_icons: ^1.0.8
  audioplayers: ^3.0.1 # Corrigido para estar na seção de dependências

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/victory_sound.mp3
    - assets/sounds/defeat_sound.mp3
